// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package restapi2

import (
	"github.com/kyrylolytvynovskyi/lets-go-chat/internal/pkg/service"
)

// Injectors from wire.go:

func InitializeServer(wsAddr string) *server {
	user := service.NewUserInMemory()
	restapi2Server := newServer(wsAddr, user)
	return restapi2Server
}
